const blogs = [
  {
    id: 1,
    title: "Understanding React",
    summary: "An introduction to React and its core concepts.",
    content: "React is a JavaScript library for building user interfaces...",
    author: "John Doe",
    image: "react.png",
  },
  {
    id: 2,
    title: "Why Blogging Matters",
    summary: "Exploring the importance of blogging in modern tech.",
    content: "Blogging is a way to share knowledge, express opinions...",
    author: "Jane Smith",
    image:"bb.avif",
  },
  {
    id: 3,
    title: "The Power of JavaScript",
    summary: "A deep dive into JavaScript and its impact on web development.",
    content: "JavaScript is a versatile programming language used in modern web development...",
    author: "Alice Johnson",
    image:"js.jpg",
  },
  {
    id: 4,
    title: "CSS for Beginners",
    summary: "Understanding the fundamentals of CSS for styling web pages.",
    content: "CSS (Cascading Style Sheets) is essential for designing visually appealing websites...",
    author: "Bob Williams",
    image:"css.avif",
  },
  {
    id: 5,
    title: "Mastering Node.js",
    summary: "An overview of Node.js and how it enables server-side JavaScript.",
    content: "Node.js allows developers to use JavaScript outside the browser to build scalable applications...",
    author: "Charlie Davis",
    image:"node.png",
  },
  {
    id: 6,
    title: "The Importance of UX/UI Design",
    summary: "How great UX/UI design improves user experience and engagement.",
    content: "User experience (UX) and user interface (UI) design play a crucial role in modern web applications...",
    author: "Diana Roberts",
    image:"uiux.jpeg",
  },
  {
    id: 7,
    title: "Getting Started with TypeScript",
    summary: "Why TypeScript is a great choice for large-scale JavaScript applications.",
    content: "TypeScript is a strongly typed superset of JavaScript that enhances code quality and maintainability...",
    author: "Edward Brown",
    image:"typescript.jpeg",
  },
];
export default blogs;
